# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7b5a1e0ee82815dc6dee25be7b683fca2e8679872a62be9c88846e7f6afdf63db9ed59b5e9b1d790c105bc4f655484a0cd3e3d8113a2bf0fdb46580a0dd3de5

test:
  secret_key_base: ef48b5e4e925fc40c7cbe6a252cf72bec7158cdb22c5525d09ec69d6cb0e2fa81cb029eec590798eb1650a071b90a7d7ff55c69540562e806a6702e0b9525dfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
